### ISSUE TITLE
`np.diag` not found in `extra.py`

### ISSUE THREAD

**Issue by Jushan-Randy-Chen** [liboyue/Network-Distributed-Algorithm#2]
I believe I should change `np.diag` to `xp.diag` in `EXTRA.py`?

**Comment by liboyue** [comment]
Please add `import numpy as np` to the beginning of this file. `__init__` is executed on CPUs so it should be `np.diag`. I'll update the code after some testing, thanks for the feedback!

**Comment by Jushan-Randy-Chen** [comment]
thank you!
