### ISSUE TITLE
how is the training data generated randomly in the base `Problem` class?

### ISSUE THREAD

**Issue by Jushan-Randy-Chen** [liboyue/Network-Distributed-Algorithm#5]
Hi,

I am a little confused over how the `dataset` in the base `Problem` class is randomly generated. In the code, I cannot find the following function named `generate_data()`:

```

if dataset == 'random':
            self.m_total = m * n_agent      # Total number of data samples of all agents
            self.generate_data()
        else:
```

I wonder if this is a function embedded in `numpy` or some other packages?

Thanks

**Comment by Jushan-Randy-Chen** [comment]
found where the function is

**Comment by liboyue** [comment]
The function in base class is just a place holder. You need to implement your own in your problem.
