### ISSUE TITLE
The algorithms e.g. SGD,DSGD always diverge 

### ISSUE THREAD

**Issue by Forshining** [liboyue/Network-Distributed-Algorithm#6]
Maybe there are some subtle wrong in this code? and I've found this error:

Process Process-8:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/true_nobility/Desktop/Network-Distributed-Algorithm-master/nda/experiment_utils/utils.py", line 21, in multi_process_helper
    log.info(f'{opt.get_name()} started')
AttributeError: 'str' object has no attribute 'get_name'

How could solve this problem

**Comment by liboyue** [comment]
Can you share code to reproduce those issues?

**Comment by Forshining** [comment]
I just copy your code in my pycharm without modifying anything. If I run the linear_regression.py in the experiment folder then it will produce these issues.

**Comment by liboyue** [comment]
What is the folder structure? Did you install this package? And which Python binary are you using? This code should work, I guess it is a Python issue.

**Comment by Forshining** [comment]
![WechatIMG52](https://user-images.githubusercontent.com/91770868/204177107-6d428a93-e6af-4020-b169-19be90142de1.jpeg)

The folder structure is here
I just want to reproduce your experiments
But the result is as follows
Python 3.9
<img width="1001" alt="WeChat6db245d3ba9cfa6d5da392aa06afc11b" src="https://user-images.githubusercontent.com/91770868/204177353-7b082507-4acc-4268-bd63-ee3296891f2e.png">

**Comment by Forshining** [comment]
The DGD_tracking algorithm seems to be too slow to converge

**Comment by Forshining** [comment]
![531669619424_ pic](https://user-images.githubusercontent.com/91770868/204215735-9bac1bc6-21f1-4f8f-a6e3-42cde51cf9d0.jpg)

**Comment by Forshining** [comment]
![1(tracking 2 10)](https://user-images.githubusercontent.com/91770868/204266292-9f519b44-bd04-43a3-8af6-ec50121217a7.png)
![1(tracking 10)](https://user-images.githubusercontent.com/91770868/204266306-310126d4-4971-440f-8074-8495456f9cd1.png)

In addition, when I try to only modify the iteration rounds of DGD_tracking algorithm, I found that the convergence performance went poor. Therefore, I suspect that maybe there are some sharing variables in these two algorithms so that it will influence another algorithm's performance when I modify the parameters of the other algorithms. I think you could check if there is anything wrong in this aspect. Thanks for your precious time!

**Comment by liboyue** [comment]
> I just want to reproduce your experiments

Which paper are you trying to reproduce? Please follow the links in README.md for specific papers. There may be some randomness, so that each run may be slightly different.

> The DGD_tracking algorithm seems to be too slow to converge

This is because it's dependency on kappa. Using a small kappa will make it much faster. But this has nothing to do with the code. If you can use GPUs, run time will be roughly 3 - 20x faster.

> I think you could check if there is anything wrong in this aspect

It may be different for each run because there is some randomness. Variables are not shared because each algorithm runs in a separate process, and Python will copy everything by default. Could you point out where the sharing happens so that I can fix it? Thanks!

I fixed `destress.py`, please update your code.

**Comment by Forshining** [comment]
Thanks for your help!
